### ISSUE TITLE
table 样式会有问题

### ISSUE THREAD

**Issue by huangyangme** [zhanziyang/wxmlify#4]
是否尚未对 table 做优化呢？

**Comment by zhanziyang** [comment]
最新版支持table啦，请重新下载。

默认是没有样式的：

![image](https://user-images.githubusercontent.com/10041024/35952565-98900b92-0cbb-11e8-9715-6050e96d7dd7.png)

你可以在 wxss 中自行对样式进行调整：

![image](https://user-images.githubusercontent.com/10041024/35952597-ba4bdc70-0cbb-11e8-93c4-7b1ccc2f1a4b.png)

上图所用样式示例：
```css
.wxmlified-table.table {
  /* table 的样式 */
  border: 1rpx solid #acacac;
}

.wxmlified-table.tr {
  /* tr 的样式 */
  border-bottom: 1rpx solid #acacac;
}

.wxmlified-table.tr:last-child {
  border-bottom:0;
}

.wxmlified-table.th, .wxmlified-table.td {
  /* th,td 的样式 */
  border-right: 1rpx solid #acacac;
  line-height: 2;
}

.wxmlified-table.th:last-child, .wxmlified-table.td:last-child {
  border-right: none;
}

.wxmlified-table.th {
  font-weight: bold;
}
```
